# Generated by Django 2.2.7 on 2020-11-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApplicationWords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='option6',
            field=models.CharField(default='Немає правильної відповіді', max_length=100),
        ),
    ]
